import nltk
import copy
from collections import defaultdict

def defRelation():
	tagged_rel = dict()
	rels = ["Synonym", "IsA", "RelatedTo", "HasA", "CreatedBy", "PartOf", "AtLocation", "LocatedNear", "DefinedAs",\
			"SymbolOf", "ReceivesAction", "HasPrerequisite", "MadeOf", "HasProperty", "UsedFor", "MotivatedByGoal",\
			"CapableOf", "Desires", "CausesDesire", "HasLastSubevent", "HasFirstSubevent", "HasSubevent", "Causes",\
			"NotIsA", "NotRelatedTo", "NotHasA", "NotCreatedBy", "NotPartOf", "NotAtLocation", "NotLocatedNear", \
			"NotDefinedAs", "NotSymbolOf", "NotReceivesAction", "NotHasPrerequisite", "NotMadeOf", "NotHasProperty",\
			"NotUsedFor", "NotMotivatedByGoal", "NotCapableOf", "NotDesires", "NotCausesDesire", "NotHasLastSubevent",\
			"NotHasFirstSubevent", "NotHasSubevent", "NotCauses",]
	tagged_rel["n,n"]	  = ["IsA"]
	tagged_rel["n,n"]    += ["Synonym"]
	tagged_rel["n,n"]    += ["RelatedTo"]
	tagged_rel["n,n"]    += ["HasA"]
	tagged_rel["n,n"]    += ["CreatedBy"]
	tagged_rel["n,n"]    += ["PartOf"]
	tagged_rel["n,n"]    += ["AtLocation"]
	tagged_rel["n,n"]    += ["LocatedNear"]
	tagged_rel["n,n"]    += ["DefinedAs"]
	tagged_rel["n,n"]    += ["SymbolOf"]
	tagged_rel["n,n"]    += ["ReceivesAction"]
	tagged_rel["n,n"]    += ["HasPrerequisite"]
	tagged_rel["n,n"]    += ["MadeOf"]
	tagged_rel["n,n"]    += ["HasProperty"]
	tagged_rel["n,v"]	  = ["UsedFor"]
	tagged_rel["n,v"]    += ["RelatedTo"]
	tagged_rel["n,v"]    += ["MotivatedByGoal"]
	tagged_rel["n,v"]    += ["CapableOf"]
	tagged_rel["n,v"]    += ["Desires"]
	tagged_rel["n,v"]    += ["CreatedBy"]
	tagged_rel["n,v"]    += ["HasPrerequisite"]
	tagged_rel["n,v"]    += ["CausesDesire"]
	tagged_rel["n,adj"]   = ["HasProperty"]
	tagged_rel["n,adj"]  += ["RelatedTo"]
	tagged_rel["n,adv"]   = ["RelatedTo"]
	tagged_rel["n,dt"]    = ["RelatedTo"]
	tagged_rel["n,adv"]   = ["RelatedTo"]
	tagged_rel["n,cc"]    = ["RelatedTo"]
	tagged_rel["n,n"]	 += ["NotIsA"]
	tagged_rel["n,n"]    += ["NotRelatedTo"]
	tagged_rel["n,n"]    += ["NotHasA"]
	tagged_rel["n,n"]    += ["NotCreatedBy"]
	tagged_rel["n,n"]    += ["NotPartOf"]
	tagged_rel["n,n"]    += ["NotAtLocation"]
	tagged_rel["n,n"]    += ["NotLocatedNear"]
	tagged_rel["n,n"]    += ["NotDefinedAs"]
	tagged_rel["n,n"]    += ["NotSymbolOf"]
	tagged_rel["n,n"]    += ["NotReceivesAction"]
	tagged_rel["n,n"]    += ["NotHasPrerequisite"]
	tagged_rel["n,n"]    += ["NotMadeOf"]
	tagged_rel["n,n"]    += ["NotHasProperty"]
	tagged_rel["n,v"]	 += ["NotUsedFor"]
	tagged_rel["n,v"]    += ["NotRelatedTo"]
	tagged_rel["n,v"]    += ["NotMotivatedByGoal"]
	tagged_rel["n,v"]    += ["NotCapableOf"]
	tagged_rel["n,v"]    += ["NotDesires"]
	tagged_rel["n,v"]    += ["NotCreatedBy"]
	tagged_rel["n,v"]    += ["NotHasPrerequisite"]
	tagged_rel["n,v"]    += ["NotCausesDesire"]
	tagged_rel["n,adj"]  += ["NotHasProperty"]
	tagged_rel["n,adj"]  += ["NotRelatedTo"]
	tagged_rel["n,adv"]   = ["NotRelatedTo"]
	tagged_rel["n,dt"]    = ["NotRelatedTo"]
	tagged_rel["n,cc"]    = ["NotRelatedTo"]
	
	tagged_rel["v,n"]	  = ["Causes"]
	tagged_rel["v,n"]    += ["HasLastSubevent"]
	tagged_rel["v,n"]    += ["RelatedTo"]
	tagged_rel["v,n"]    += ["MotivatedByGoal"]
	tagged_rel["v,n"]    += ["HasFirstSubevent"]
	tagged_rel["v,n"]    += ["HasPrerequisite"]
	tagged_rel["v,n"]    += ["HasSubevent"]
	tagged_rel["v,v"]	  = ["Causes"]
	tagged_rel["v,v"]    += ["MotivatedByGoal"]
	tagged_rel["v,v"]    += ["RelatedTo"]
	tagged_rel["v,v"]    += ["Synonym"]
	tagged_rel["v,v"]    += ["HasFirstSubevent"]
	tagged_rel["v,v"]    += ["HasPrerequisite"]
	tagged_rel["v,v"]    += ["HasSubevent"]
	tagged_rel["v,v"]    += ["HasLastSubevent"]
	tagged_rel["v,dt"]    = ["MotivatedByGoal"]
	tagged_rel["v,dt"]   += ["HasProperty"]
	tagged_rel["v,dt"]   += ["HasSubevent"]
	tagged_rel["v,dt"]   += ["RelatedTo"]
	tagged_rel["v,dt"]   += ["Desires"]
	tagged_rel["v,adj"]   = ["RelatedTo"]
	tagged_rel["v,adj"]  += ["MotivatedByGoal"]
	tagged_rel["v,adj"]  += ["HasLastSubevent"]
	tagged_rel["v,adj"]	 += ["Causes"]
	tagged_rel["v,adj"]  += ["HasSubevent"]
	tagged_rel["v,adv"]   = ["RelatedTo"]
	tagged_rel["v,cc"]    = ["RelatedTo"]
	tagged_rel["v,n"]	 += ["NotCauses"]
	tagged_rel["v,n"]    += ["NotHasLastSubevent"]
	tagged_rel["v,n"]    += ["NotRelatedTo"]
	tagged_rel["v,n"]    += ["NotMotivatedByGoal"]
	tagged_rel["v,n"]    += ["NotHasFirstSubevent"]
	tagged_rel["v,n"]    += ["NotHasPrerequisite"]
	tagged_rel["v,n"]    += ["NotHasSubevent"]
	tagged_rel["v,v"]	 += ["NotCauses"]
	tagged_rel["v,v"]    += ["NotMotivatedByGoal"]
	tagged_rel["v,v"]    += ["NotRelatedTo"]
	tagged_rel["v,v"]    += ["NotHasFirstSubevent"]
	tagged_rel["v,v"]    += ["NotHasPrerequisite"]
	tagged_rel["v,v"]    += ["NotHasSubevent"]
	tagged_rel["v,v"]    += ["NotHasLastSubevent"]
	tagged_rel["v,dt"]    = ["NotMotivatedByGoal"]
	tagged_rel["v,dt"]   += ["NotHasProperty"]
	tagged_rel["v,dt"]   += ["NotHasSubevent"]
	tagged_rel["v,dt"]   += ["NotRelatedTo"]
	tagged_rel["v,dt"]   += ["NotDesires"]
	tagged_rel["v,adj"]  += ["NotRelatedTo"]
	tagged_rel["v,adj"]  += ["NotMotivatedByGoal"]
	tagged_rel["v,adj"]  += ["NotHasLastSubevent"]
	tagged_rel["v,adj"]	 += ["NotCauses"]
	tagged_rel["v,adj"]  += ["NotHasSubevent"]
	tagged_rel["v,adv"]   = ["NotRelatedTo"]
	tagged_rel["v,cc"]    = ["NotRelatedTo"]
	
	tagged_rel["adj,n"]   = ["RelatedTo"]
	tagged_rel["adj,n"]  += ["SymbolOf"]
	tagged_rel["adj,n"]  += ["CausesDesire"]
	tagged_rel["adj,v"]   = ["RelatedTo"]
	tagged_rel["adj,v"]  += ["MotivatedByGoal"]
	tagged_rel["adj,v"]  += ["CausesDesire"]
	tagged_rel["adj,v"]	 += ["UsedFor"]
	tagged_rel["adj,adj"] = ["Synonym"]
	tagged_rel["adj,adj"]+= ["RelatedTo"]
	tagged_rel["adj,adj"]+= ["HasProperty"]
	tagged_rel["adj,dt"]  = ["RelatedTo"]
	tagged_rel["adj,adv"] = ["RelatedTo"]
	tagged_rel["adj,cc"]  = ["RelatedTo"]
	tagged_rel["adj,n"]  += ["NotRelatedTo"]
	tagged_rel["adj,n"]  += ["NotSymbolOf"]
	tagged_rel["adj,n"]  += ["NotCausesDesire"]
	tagged_rel["adj,v"]  += ["NotRelatedTo"]
	tagged_rel["adj,v"]  += ["NotMotivatedByGoal"]
	tagged_rel["adj,v"]  += ["NotCausesDesire"]
	tagged_rel["adj,v"]	 += ["NotUsedFor"]
	tagged_rel["adj,adj"]+= ["NotRelatedTo"]
	tagged_rel["adj,adj"]+= ["NotHasProperty"]
	tagged_rel["adj,dt"]  = ["NotRelatedTo"]
	tagged_rel["adj,adv"] = ["NotRelatedTo"]
	tagged_rel["adj,cc"]  = ["NotRelatedTo"]

	tagged_rel["adv,n"]   = ["RelatedTo"]
	tagged_rel["adv,n"]  += ["SymbolOf"]
	tagged_rel["adv,n"]  += ["CausesDesire"]
	tagged_rel["adv,v"]   = ["RelatedTo"]
	tagged_rel["adv,v"]  += ["MotivatedByGoal"]
	tagged_rel["adv,v"]  += ["CausesDesire"]
	tagged_rel["adv,v"]	 += ["UsedFor"]
	tagged_rel["adv,adj"] = ["RelatedTo"]
	tagged_rel["adv,adj"]+= ["Synonym"]
	tagged_rel["adv,adj"]+= ["HasProperty"]
	tagged_rel["adv,dt"]  = ["RelatedTo"]
	tagged_rel["adv,adv"] = ["RelatedTo"]
	tagged_rel["adv,cc"]  = ["RelatedTo"]
	tagged_rel["adv,n"]  += ["NotRelatedTo"]
	tagged_rel["adv,n"]  += ["NotSymbolOf"]
	tagged_rel["adv,n"]  += ["NotCausesDesire"]
	tagged_rel["adv,v"]  += ["NotRelatedTo"]
	tagged_rel["adv,v"]  += ["NotMotivatedByGoal"]
	tagged_rel["adv,v"]  += ["NotCausesDesire"]
	tagged_rel["adv,v"]	 += ["NotUsedFor"]
	tagged_rel["adv,adj"]+= ["NotRelatedTo"]
	tagged_rel["adv,adj"]+= ["NotHasProperty"]
	tagged_rel["adv,dt"]  = ["NotRelatedTo"]
	tagged_rel["adv,adv"] = ["NotRelatedTo"]
	tagged_rel["adv,cc"]  = ["NotRelatedTo"]
	
	tagged_rel["dt,n"]	  = ["IsA"]
	tagged_rel["dt,n"]   += ["Synonym"]
	tagged_rel["dt,n"]   += ["RelatedTo"]
	tagged_rel["dt,n"]   += ["CreatedBy"]
	tagged_rel["dt,n"]   += ["PartOf"]
	tagged_rel["dt,n"]   += ["AtLocation"]
	tagged_rel["dt,n"]   += ["LocatedNear"]
	tagged_rel["dt,n"]   += ["DefinedAs"]
	tagged_rel["dt,n"]   += ["SymbolOf"]
	tagged_rel["dt,n"]   += ["ReceivesAction"]
	tagged_rel["dt,n"]   += ["HasPrerequisite"]
	tagged_rel["dt,n"]   += ["MadeOf"]
	tagged_rel["dt,n"]   += ["HasProperty"]
	tagged_rel["dt,v"]	  = ["UsedFor"]
	tagged_rel["dt,v"]   += ["RelatedTo"]
	tagged_rel["dt,v"]   += ["MotivatedByGoal"]
	tagged_rel["dt,v"]   += ["CapableOf"]
	tagged_rel["dt,v"]   += ["Desires"]
	tagged_rel["dt,v"]   += ["CreatedBy"]
	tagged_rel["dt,v"]   += ["HasPrerequisite"]
	tagged_rel["dt,v"]   += ["CausesDesire"]
	tagged_rel["dt,adj"]  = ["HasProperty"]
	tagged_rel["dt,adj"] += ["RelatedTo"]
	tagged_rel["dt,dt"]   = ["RelatedTo"]
	tagged_rel["dt,adv"]  = ["RelatedTo"]
	tagged_rel["dt,cc"]   = ["RelatedTo"]
	tagged_rel["dt,n"]	 += ["NotIsA"]
	tagged_rel["dt,n"]   += ["NotRelatedTo"]
	tagged_rel["dt,n"]   += ["NotCreatedBy"]
	tagged_rel["dt,n"]   += ["NotPartOf"]
	tagged_rel["dt,n"]   += ["NotAtLocation"]
	tagged_rel["dt,n"]   += ["NotLocatedNear"]
	tagged_rel["dt,n"]   += ["NotDefinedAs"]
	tagged_rel["dt,n"]   += ["NotSymbolOf"]
	tagged_rel["dt,n"]   += ["NotReceivesAction"]
	tagged_rel["dt,n"]   += ["NotHasPrerequisite"]
	tagged_rel["dt,n"]   += ["NotMadeOf"]
	tagged_rel["dt,n"]   += ["NotHasProperty"]
	tagged_rel["dt,v"]	 += ["NotUsedFor"]
	tagged_rel["dt,v"]   += ["NotRelatedTo"]
	tagged_rel["dt,v"]   += ["NotMotivatedByGoal"]
	tagged_rel["dt,v"]   += ["NotCapableOf"]
	tagged_rel["dt,v"]   += ["NotDesires"]
	tagged_rel["dt,v"]   += ["NotCreatedBy"]
	tagged_rel["dt,v"]   += ["NotHasPrerequisite"]
	tagged_rel["dt,v"]   += ["NotCausesDesire"]
	tagged_rel["dt,adj"] += ["NotHasProperty"]
	tagged_rel["dt,adj"] += ["NotRelatedTo"]
	tagged_rel["dt,dt"]   = ["NotRelatedTo"]
	tagged_rel["dt,adv"]  = ["NotRelatedTo"]
	tagged_rel["dt,cc"]   = ["NotRelatedTo"]

	tagged_rel["cc,n"]    = ["RelatedTo"]
	tagged_rel["cc,n"]   += ["PartOf"]
	tagged_rel["cc,n"]   += ["LocatedNear"]
	tagged_rel["cc,n"]   += ["Synonym"]
	tagged_rel["cc,v"]    = ["RelatedTo"]
	tagged_rel["cc,adj"]  = ["RelatedTo"]
	tagged_rel["cc,dt"]   = ["RelatedTo"]
	tagged_rel["cc,adv"]  = ["RelatedTo"]
	tagged_rel["cc,cc"]   = ["RelatedTo"]
	tagged_rel["cc,n"]   += ["NotRelatedTo"]
	tagged_rel["cc,n"]   += ["NotPartOf"]
	tagged_rel["cc,n"]   += ["NotLocatedNear"]
	tagged_rel["cc,v"]   += ["NotRelatedTo"]
	tagged_rel["cc,adj"] += ["NotRelatedTo"]
	tagged_rel["cc,dt"]   = ["NotRelatedTo"]
	tagged_rel["cc,adv"]  = ["NotRelatedTo"]
	tagged_rel["cc,cc"]   = ["NotRelatedTo"]
	return tagged_rel, rels

def readPosTag(filename):
	posDict = dict()
	f = open(filename, 'rb')
	for line in f:
		posDict[line.split(" ")[-1][:-1]] = line.split(" ")[0]
	return posDict


		

